language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
install:
  - pip install -e .[tests]
before_script:
  - pip install python-coveralls pytest-cov
script:
  - py.test tests/ --cov=src
after_success:
  - coveralls